### ISSUE TITLE
failed parsing rebar.config of relx

### ISSUE THREAD

**Issue by comtihon** [machinezone/python_etf#6]
Hi!
I am trying to parse `https://github.com/erlware/relx/blob/master/rebar.config` and get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/erl_terms/erl_terms_core.py", line 55, in lex
    return grammar.parse(nocomments)
  File "/usr/lib/python3.6/site-packages/parsimonious/grammar.py", line 123, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/usr/lib/python3.6/site-packages/parsimonious/expressions.py", line 112, in parse
    raise IncompleteParseError(text, node.end, self)
parsimonious.exceptions.IncompleteParseError: Rule 'entry' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '{escript_emu_args, "' (line 11, column 1).

```

**Comment by parsifal-47** [comment]
Fixed, thanks for reporting this issue!
